### ISSUE TITLE
Spike: Investigate mapping problem events to xAPI statements

### ISSUE THREAD

**Issue by e0d** [openedx/data-wg#15]
If we want to declare xAPI our official event representation, we'll need to ensure that critical events can be cleanly mapped into xAPI statements.

Let's do a spike that attempts to map [problem related events](https://edx.readthedocs.io/projects/devdata/en/stable/internal_data_formats/tracking_logs.html#problem) into xAPI

The output would be a document proposing a mapping for each problem event type.

**Comment by MaferMazu** [comment]
I could commit myself to help with half of the problems, and it would be for 1 or 2 weeks, right now I'm a bit full but I can help :D

I was looking at an example of this using the [enrollment.activate](https://edx.readthedocs.io/projects/devdata/en/latest/internal_data_formats/tracking_logs/student_event_types.html#edx-course-enrollment-activated-and-edx-course-enrollment-deactivated) event and its [mapping in xAPI](https://github.com/openedx/event-routing-backends/blob/master/docs/event-mapping/xAPI_mapping.rst#edx-course-enrollment-activated), but I wanted to know if any of you have a document that says what are the best practices for mapping to xAPI.

**Comment by jmakowski1123** [comment]
close in favor of xAPI m1 and m2
