### ISSUE TITLE
Spike: Review and report on event_types in use in your organizations data pipeline

### ISSUE THREAD

**Issue by e0d** [openedx/data-wg#16]
In order to create a backlog of critical Open edX tracking event to map to xAPI events, we should analyze the use of event_types in the real world.

We'd like several organizations to review and report back on which event_types they are currently using to produce analytics used by people or processes in their instances.

**Comment by angonz** [comment]
We are using:

- all video events (load, play, pause, seek, etc.)
- all forum events (reply, thread created, read, etc.)
- edx.ui.lms.link_clicked to track file downloads
- login events
- all events en general, to track user activity

**Comment by pomegranited** [comment]
FYI a full list of event types is here: [edX Research Guide > Alphabetical Event List](https://edx.readthedocs.io/projects/devdata/en/stable/internal_data_formats/event_list.html)

**Comment by MaferMazu** [comment]
In eduNEXT we use the events used by Insights.

**Comment by bmtcril** [comment]
I'm calling this done as we haven't had any recent responses, but did get a large dump of edx.org event data to work with. Thanks for the responses, all.
